# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MRRenderLayerPass.ui'
#
# Created: Thu Dec 22 17:29:51 2011
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_root(object):
    def setupUi(self, root):
        root.setObjectName(_fromUtf8("root"))
        root.resize(353, 600)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        root.setFont(font)
        root.setWindowTitle(QtGui.QApplication.translate("root", "Mental Ray Render Layer Tool V1.0 (37digital)", None, QtGui.QApplication.UnicodeUTF8))
        root.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtGui.QWidget(root)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Tab_layer = QtGui.QWidget()
        self.Tab_layer.setObjectName(_fromUtf8("Tab_layer"))
        self.layoutWidget = QtGui.QWidget(self.Tab_layer)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.Tab_layer)
        self.groupBox.setGeometry(QtCore.QRect(10, 320, 311, 211))
        self.groupBox.setTitle(QtGui.QApplication.translate("root", "Render Status:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_renderStatus_02 = QtGui.QHBoxLayout()
        self.horizontalLayout_renderStatus_02.setObjectName(_fromUtf8("horizontalLayout_renderStatus_02"))
        self.checkBox_castsShadows = QtGui.QCheckBox(self.groupBox)
        self.checkBox_castsShadows.setEnabled(True)
        self.checkBox_castsShadows.setText(QtGui.QApplication.translate("root", "Casts Shadows", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_castsShadows.setChecked(True)
        self.checkBox_castsShadows.setObjectName(_fromUtf8("checkBox_castsShadows"))
        self.horizontalLayout_renderStatus_02.addWidget(self.checkBox_castsShadows)
        self.checkBox_receiveShadows = QtGui.QCheckBox(self.groupBox)
        self.checkBox_receiveShadows.setText(QtGui.QApplication.translate("root", "Receive Shadows", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_receiveShadows.setChecked(True)
        self.checkBox_receiveShadows.setObjectName(_fromUtf8("checkBox_receiveShadows"))
        self.horizontalLayout_renderStatus_02.addWidget(self.checkBox_receiveShadows)
        self.verticalLayout_2.addLayout(self.horizontalLayout_renderStatus_02)
        self.horizontalLayout_renderStatus_03 = QtGui.QHBoxLayout()
        self.horizontalLayout_renderStatus_03.setObjectName(_fromUtf8("horizontalLayout_renderStatus_03"))
        self.checkBox_motionBlur = QtGui.QCheckBox(self.groupBox)
        self.checkBox_motionBlur.setText(QtGui.QApplication.translate("root", "Motion Blur", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_motionBlur.setChecked(True)
        self.checkBox_motionBlur.setObjectName(_fromUtf8("checkBox_motionBlur"))
        self.horizontalLayout_renderStatus_03.addWidget(self.checkBox_motionBlur)
        self.checkBox_primaryVisibility = QtGui.QCheckBox(self.groupBox)
        self.checkBox_primaryVisibility.setText(QtGui.QApplication.translate("root", "Primary Visibility", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_primaryVisibility.setChecked(True)
        self.checkBox_primaryVisibility.setObjectName(_fromUtf8("checkBox_primaryVisibility"))
        self.horizontalLayout_renderStatus_03.addWidget(self.checkBox_primaryVisibility)
        self.verticalLayout_2.addLayout(self.horizontalLayout_renderStatus_03)
        self.horizontalLayout_renderStatus_04 = QtGui.QHBoxLayout()
        self.horizontalLayout_renderStatus_04.setObjectName(_fromUtf8("horizontalLayout_renderStatus_04"))
        self.checkBox_smoothShading = QtGui.QCheckBox(self.groupBox)
        self.checkBox_smoothShading.setText(QtGui.QApplication.translate("root", "Smooth Shading", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_smoothShading.setChecked(True)
        self.checkBox_smoothShading.setObjectName(_fromUtf8("checkBox_smoothShading"))
        self.horizontalLayout_renderStatus_04.addWidget(self.checkBox_smoothShading)
        self.checkBox_visibleInReflections = QtGui.QCheckBox(self.groupBox)
        self.checkBox_visibleInReflections.setText(QtGui.QApplication.translate("root", "Visible In Reflections", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_visibleInReflections.setChecked(True)
        self.checkBox_visibleInReflections.setObjectName(_fromUtf8("checkBox_visibleInReflections"))
        self.horizontalLayout_renderStatus_04.addWidget(self.checkBox_visibleInReflections)
        self.verticalLayout_2.addLayout(self.horizontalLayout_renderStatus_04)
        self.horizontalLayout_renderStatus_05 = QtGui.QHBoxLayout()
        self.horizontalLayout_renderStatus_05.setObjectName(_fromUtf8("horizontalLayout_renderStatus_05"))
        self.checkBox_visibleInRefractions = QtGui.QCheckBox(self.groupBox)
        self.checkBox_visibleInRefractions.setText(QtGui.QApplication.translate("root", "Visible In Refractions", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_visibleInRefractions.setChecked(True)
        self.checkBox_visibleInRefractions.setObjectName(_fromUtf8("checkBox_visibleInRefractions"))
        self.horizontalLayout_renderStatus_05.addWidget(self.checkBox_visibleInRefractions)
        self.checkBox_doubleSided = QtGui.QCheckBox(self.groupBox)
        self.checkBox_doubleSided.setText(QtGui.QApplication.translate("root", "Double Sided", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_doubleSided.setChecked(True)
        self.checkBox_doubleSided.setTristate(False)
        self.checkBox_doubleSided.setObjectName(_fromUtf8("checkBox_doubleSided"))
        self.horizontalLayout_renderStatus_05.addWidget(self.checkBox_doubleSided)
        self.verticalLayout_2.addLayout(self.horizontalLayout_renderStatus_05)
        self.checkBox_opposite = QtGui.QCheckBox(self.groupBox)
        self.checkBox_opposite.setEnabled(False)
        self.checkBox_opposite.setText(QtGui.QApplication.translate("root", "Opposite", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_opposite.setChecked(False)
        self.checkBox_opposite.setObjectName(_fromUtf8("checkBox_opposite"))
        self.verticalLayout_2.addWidget(self.checkBox_opposite)
        self.pushButton_RS_apply = QtGui.QPushButton(self.groupBox)
        self.pushButton_RS_apply.setText(QtGui.QApplication.translate("root", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_RS_apply.setObjectName(_fromUtf8("pushButton_RS_apply"))
        self.verticalLayout_2.addWidget(self.pushButton_RS_apply)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.groupBox_2 = QtGui.QGroupBox(self.Tab_layer)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 170, 311, 141))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("root", "Create Materials:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.widget = QtGui.QWidget(self.groupBox_2)
        self.widget.setGeometry(QtCore.QRect(10, 30, 291, 95))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_createMaterials_02 = QtGui.QHBoxLayout()
        self.horizontalLayout_createMaterials_02.setObjectName(_fromUtf8("horizontalLayout_createMaterials_02"))
        self.pushButton_CM_black = QtGui.QPushButton(self.widget)
        self.pushButton_CM_black.setText(QtGui.QApplication.translate("root", "Black", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_CM_black.setObjectName(_fromUtf8("pushButton_CM_black"))
        self.horizontalLayout_createMaterials_02.addWidget(self.pushButton_CM_black)
        self.pushButton_CM_blackNoAlpha = QtGui.QPushButton(self.widget)
        self.pushButton_CM_blackNoAlpha.setText(QtGui.QApplication.translate("root", "Black No Alpha", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_CM_blackNoAlpha.setObjectName(_fromUtf8("pushButton_CM_blackNoAlpha"))
        self.horizontalLayout_createMaterials_02.addWidget(self.pushButton_CM_blackNoAlpha)
        self.verticalLayout.addLayout(self.horizontalLayout_createMaterials_02)
        self.horizontalLayout_createMaterials_03 = QtGui.QHBoxLayout()
        self.horizontalLayout_createMaterials_03.setObjectName(_fromUtf8("horizontalLayout_createMaterials_03"))
        self.pushButton_CM_red = QtGui.QPushButton(self.widget)
        self.pushButton_CM_red.setText(QtGui.QApplication.translate("root", "Red", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_CM_red.setObjectName(_fromUtf8("pushButton_CM_red"))
        self.horizontalLayout_createMaterials_03.addWidget(self.pushButton_CM_red)
        self.pushButton_CM_green = QtGui.QPushButton(self.widget)
        self.pushButton_CM_green.setText(QtGui.QApplication.translate("root", "Green", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_CM_green.setObjectName(_fromUtf8("pushButton_CM_green"))
        self.horizontalLayout_createMaterials_03.addWidget(self.pushButton_CM_green)
        self.pushButton_CM_blue = QtGui.QPushButton(self.widget)
        self.pushButton_CM_blue.setText(QtGui.QApplication.translate("root", "Blue", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_CM_blue.setObjectName(_fromUtf8("pushButton_CM_blue"))
        self.horizontalLayout_createMaterials_03.addWidget(self.pushButton_CM_blue)
        self.verticalLayout.addLayout(self.horizontalLayout_createMaterials_03)
        self.horizontalLayout_createMaterials_04 = QtGui.QHBoxLayout()
        self.horizontalLayout_createMaterials_04.setObjectName(_fromUtf8("horizontalLayout_createMaterials_04"))
        self.pushButton_CM_useBackground = QtGui.QPushButton(self.widget)
        self.pushButton_CM_useBackground.setText(QtGui.QApplication.translate("root", "Use Background", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_CM_useBackground.setObjectName(_fromUtf8("pushButton_CM_useBackground"))
        self.horizontalLayout_createMaterials_04.addWidget(self.pushButton_CM_useBackground)
        self.pushButton_CM_zDepth = QtGui.QPushButton(self.widget)
        self.pushButton_CM_zDepth.setText(QtGui.QApplication.translate("root", "Z Depth", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_CM_zDepth.setObjectName(_fromUtf8("pushButton_CM_zDepth"))
        self.horizontalLayout_createMaterials_04.addWidget(self.pushButton_CM_zDepth)
        self.verticalLayout.addLayout(self.horizontalLayout_createMaterials_04)
        self.groupBox_3 = QtGui.QGroupBox(self.Tab_layer)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 311, 151))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("root", "Create Render Layers:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.widget1 = QtGui.QWidget(self.groupBox_3)
        self.widget1.setGeometry(QtCore.QRect(10, 30, 291, 111))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_createRenderLayers_02 = QtGui.QHBoxLayout()
        self.horizontalLayout_createRenderLayers_02.setObjectName(_fromUtf8("horizontalLayout_createRenderLayers_02"))
        self.pushButton_CRL_color = QtGui.QPushButton(self.widget1)
        self.pushButton_CRL_color.setText(QtGui.QApplication.translate("root", "Color", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_CRL_color.setObjectName(_fromUtf8("pushButton_CRL_color"))
        self.horizontalLayout_createRenderLayers_02.addWidget(self.pushButton_CRL_color)
        self.pushButton_CRL_aO = QtGui.QPushButton(self.widget1)
        self.pushButton_CRL_aO.setText(QtGui.QApplication.translate("root", "AO", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_CRL_aO.setObjectName(_fromUtf8("pushButton_CRL_aO"))
        self.horizontalLayout_createRenderLayers_02.addWidget(self.pushButton_CRL_aO)
        self.verticalLayout_3.addLayout(self.horizontalLayout_createRenderLayers_02)
        self.horizontalLayout_createRenderLayers_03 = QtGui.QHBoxLayout()
        self.horizontalLayout_createRenderLayers_03.setObjectName(_fromUtf8("horizontalLayout_createRenderLayers_03"))
        self.pushButton_CRL_keyLight = QtGui.QPushButton(self.widget1)
        self.pushButton_CRL_keyLight.setText(QtGui.QApplication.translate("root", "Key Light", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_CRL_keyLight.setObjectName(_fromUtf8("pushButton_CRL_keyLight"))
        self.horizontalLayout_createRenderLayers_03.addWidget(self.pushButton_CRL_keyLight)
        self.pushButton_CRL_fillLight = QtGui.QPushButton(self.widget1)
        self.pushButton_CRL_fillLight.setText(QtGui.QApplication.translate("root", "Fill Light", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_CRL_fillLight.setObjectName(_fromUtf8("pushButton_CRL_fillLight"))
        self.horizontalLayout_createRenderLayers_03.addWidget(self.pushButton_CRL_fillLight)
        self.pushButton_CRL_backLight = QtGui.QPushButton(self.widget1)
        self.pushButton_CRL_backLight.setText(QtGui.QApplication.translate("root", "Back Light", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_CRL_backLight.setObjectName(_fromUtf8("pushButton_CRL_backLight"))
        self.horizontalLayout_createRenderLayers_03.addWidget(self.pushButton_CRL_backLight)
        self.verticalLayout_3.addLayout(self.horizontalLayout_createRenderLayers_03)
        self.horizontalLayout_createRenderLayers_04 = QtGui.QHBoxLayout()
        self.horizontalLayout_createRenderLayers_04.setObjectName(_fromUtf8("horizontalLayout_createRenderLayers_04"))
        self.pushButton_CRL_shadow = QtGui.QPushButton(self.widget1)
        self.pushButton_CRL_shadow.setText(QtGui.QApplication.translate("root", "Shadow", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_CRL_shadow.setObjectName(_fromUtf8("pushButton_CRL_shadow"))
        self.horizontalLayout_createRenderLayers_04.addWidget(self.pushButton_CRL_shadow)
        self.pushButton_CRL_maskRGB = QtGui.QPushButton(self.widget1)
        self.pushButton_CRL_maskRGB.setText(QtGui.QApplication.translate("root", "Mask RGB", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_CRL_maskRGB.setObjectName(_fromUtf8("pushButton_CRL_maskRGB"))
        self.horizontalLayout_createRenderLayers_04.addWidget(self.pushButton_CRL_maskRGB)
        self.verticalLayout_3.addLayout(self.horizontalLayout_createRenderLayers_04)
        self.tabWidget.addTab(self.Tab_layer, _fromUtf8(""))
        self.Tab_subSet = QtGui.QWidget()
        self.Tab_subSet.setObjectName(_fromUtf8("Tab_subSet"))
        self.listWidget = QtGui.QListWidget(self.Tab_subSet)
        self.listWidget.setGeometry(QtCore.QRect(10, 300, 201, 121))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.groupBox_4 = QtGui.QGroupBox(self.Tab_subSet)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 311, 211))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("root", "SubSets:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.widget2 = QtGui.QWidget(self.groupBox_4)
        self.widget2.setGeometry(QtCore.QRect(10, 20, 291, 184))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget2)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.scrollArea = QtGui.QScrollArea(self.widget2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 183, 178))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.pushButton_SS_new = QtGui.QPushButton(self.widget2)
        self.pushButton_SS_new.setText(QtGui.QApplication.translate("root", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_SS_new.setObjectName(_fromUtf8("pushButton_SS_new"))
        self.verticalLayout_5.addWidget(self.pushButton_SS_new)
        self.pushButton_SS_delete = QtGui.QPushButton(self.widget2)
        self.pushButton_SS_delete.setText(QtGui.QApplication.translate("root", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_SS_delete.setObjectName(_fromUtf8("pushButton_SS_delete"))
        self.verticalLayout_5.addWidget(self.pushButton_SS_delete)
        self.pushButton_SS_refresh = QtGui.QPushButton(self.widget2)
        self.pushButton_SS_refresh.setText(QtGui.QApplication.translate("root", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_SS_refresh.setObjectName(_fromUtf8("pushButton_SS_refresh"))
        self.verticalLayout_5.addWidget(self.pushButton_SS_refresh)
        self.pushButton_SS_pickObjects = QtGui.QPushButton(self.widget2)
        self.pushButton_SS_pickObjects.setText(QtGui.QApplication.translate("root", "Pick Objects", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_SS_pickObjects.setObjectName(_fromUtf8("pushButton_SS_pickObjects"))
        self.verticalLayout_5.addWidget(self.pushButton_SS_pickObjects)
        self.pushButton_SS_addObject = QtGui.QPushButton(self.widget2)
        self.pushButton_SS_addObject.setText(QtGui.QApplication.translate("root", "Add Object", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_SS_addObject.setObjectName(_fromUtf8("pushButton_SS_addObject"))
        self.verticalLayout_5.addWidget(self.pushButton_SS_addObject)
        self.pushButton_SS_removeObject = QtGui.QPushButton(self.widget2)
        self.pushButton_SS_removeObject.setText(QtGui.QApplication.translate("root", "Remove Object", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_SS_removeObject.setObjectName(_fromUtf8("pushButton_SS_removeObject"))
        self.verticalLayout_5.addWidget(self.pushButton_SS_removeObject)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.Tab_subSet, _fromUtf8(""))
        self.tab_help = QtGui.QWidget()
        self.tab_help.setObjectName(_fromUtf8("tab_help"))
        self.tabWidget.addTab(self.tab_help, _fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.tabWidget)
        root.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(root)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        root.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(root)
        self.actionOpen.setText(QtGui.QApplication.translate("root", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))

        self.retranslateUi(root)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.checkBox_doubleSided, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.checkBox_opposite.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(root)

    def retranslateUi(self, root):
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_layer), QtGui.QApplication.translate("root", "Render Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Tab_subSet), QtGui.QApplication.translate("root", "Render SubSet", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_help), QtGui.QApplication.translate("root", "Help", None, QtGui.QApplication.UnicodeUTF8))

