# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MRRenderLayerPassManager.ui'
#
# Created: Sat Feb 04 13:33:49 2012
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_root(object):
    def setupUi(self, root):
        root.setObjectName(_fromUtf8("root"))
        root.resize(1246, 727)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        root.setFont(font)
        root.setWindowTitle(QtGui.QApplication.translate("root", "Mental Ray Render Layer Manager V1.0 (37digital)", None, QtGui.QApplication.UnicodeUTF8))
        root.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtGui.QWidget(root)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_L = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_L.setMargin(0)
        self.verticalLayout_L.setObjectName(_fromUtf8("verticalLayout_L"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.pushButton_refresh = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_refresh.setText(QtGui.QApplication.translate("root", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_refresh.setObjectName(_fromUtf8("pushButton_refresh"))
        self.verticalLayout_10.addWidget(self.pushButton_refresh)
        self.comboBox_L = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_L.setObjectName(_fromUtf8("comboBox_L"))
        self.verticalLayout_10.addWidget(self.comboBox_L)
        self.verticalLayout_L.addLayout(self.verticalLayout_10)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.stackedWidget = QtGui.QStackedWidget(self.layoutWidget)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page_SL = QtGui.QWidget()
        self.page_SL.setObjectName(_fromUtf8("page_SL"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.page_SL)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.listWidget_SL = QtGui.QListWidget(self.page_SL)
        self.listWidget_SL.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.listWidget_SL.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_SL.setObjectName(_fromUtf8("listWidget_SL"))
        self.verticalLayout_9.addWidget(self.listWidget_SL)
        self.pushButton_SL_add = QtGui.QPushButton(self.page_SL)
        self.pushButton_SL_add.setText(QtGui.QApplication.translate("root", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_SL_add.setObjectName(_fromUtf8("pushButton_SL_add"))
        self.verticalLayout_9.addWidget(self.pushButton_SL_add)
        self.pushButton_SL_remove = QtGui.QPushButton(self.page_SL)
        self.pushButton_SL_remove.setText(QtGui.QApplication.translate("root", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_SL_remove.setObjectName(_fromUtf8("pushButton_SL_remove"))
        self.verticalLayout_9.addWidget(self.pushButton_SL_remove)
        self.verticalLayout_8.addLayout(self.verticalLayout_9)
        self.stackedWidget.addWidget(self.page_SL)
        self.page_CL = QtGui.QWidget()
        self.page_CL.setObjectName(_fromUtf8("page_CL"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.page_CL)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.listWidget_CL = QtGui.QListWidget(self.page_CL)
        self.listWidget_CL.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.listWidget_CL.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_CL.setObjectName(_fromUtf8("listWidget_CL"))
        self.verticalLayout_11.addWidget(self.listWidget_CL)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_layerName = QtGui.QLabel(self.page_CL)
        self.label_layerName.setText(QtGui.QApplication.translate("root", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_layerName.setObjectName(_fromUtf8("label_layerName"))
        self.horizontalLayout_4.addWidget(self.label_layerName)
        self.lineEdit_layerName = QtGui.QLineEdit(self.page_CL)
        self.lineEdit_layerName.setObjectName(_fromUtf8("lineEdit_layerName"))
        self.horizontalLayout_4.addWidget(self.lineEdit_layerName)
        self.verticalLayout_11.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_layerName_2 = QtGui.QLabel(self.page_CL)
        self.label_layerName_2.setText(QtGui.QApplication.translate("root", "Name Prefix:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_layerName_2.setObjectName(_fromUtf8("label_layerName_2"))
        self.horizontalLayout_6.addWidget(self.label_layerName_2)
        self.lineEdit_layerPrefix = QtGui.QLineEdit(self.page_CL)
        self.lineEdit_layerPrefix.setObjectName(_fromUtf8("lineEdit_layerPrefix"))
        self.horizontalLayout_6.addWidget(self.lineEdit_layerPrefix)
        self.verticalLayout_11.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_layerName_3 = QtGui.QLabel(self.page_CL)
        self.label_layerName_3.setText(QtGui.QApplication.translate("root", "Name Suffix:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_layerName_3.setObjectName(_fromUtf8("label_layerName_3"))
        self.horizontalLayout_7.addWidget(self.label_layerName_3)
        self.lineEdit_layerSuffix = QtGui.QLineEdit(self.page_CL)
        self.lineEdit_layerSuffix.setObjectName(_fromUtf8("lineEdit_layerSuffix"))
        self.horizontalLayout_7.addWidget(self.lineEdit_layerSuffix)
        self.verticalLayout_11.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_layerName_4 = QtGui.QLabel(self.page_CL)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_layerName_4.sizePolicy().hasHeightForWidth())
        self.label_layerName_4.setSizePolicy(sizePolicy)
        self.label_layerName_4.setText(QtGui.QApplication.translate("root", "Preset:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_layerName_4.setObjectName(_fromUtf8("label_layerName_4"))
        self.horizontalLayout_3.addWidget(self.label_layerName_4)
        self.comboBox_CL = QtGui.QComboBox(self.page_CL)
        self.comboBox_CL.setObjectName(_fromUtf8("comboBox_CL"))
        self.horizontalLayout_3.addWidget(self.comboBox_CL)
        self.verticalLayout_11.addLayout(self.horizontalLayout_3)
        self.pushButton_CL_add = QtGui.QPushButton(self.page_CL)
        self.pushButton_CL_add.setText(QtGui.QApplication.translate("root", "                      Add                     ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_CL_add.setObjectName(_fromUtf8("pushButton_CL_add"))
        self.verticalLayout_11.addWidget(self.pushButton_CL_add)
        self.pushButton_CL_remove = QtGui.QPushButton(self.page_CL)
        self.pushButton_CL_remove.setText(QtGui.QApplication.translate("root", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_CL_remove.setObjectName(_fromUtf8("pushButton_CL_remove"))
        self.verticalLayout_11.addWidget(self.pushButton_CL_remove)
        self.pushButton_CL_apply = QtGui.QPushButton(self.page_CL)
        self.pushButton_CL_apply.setText(QtGui.QApplication.translate("root", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_CL_apply.setObjectName(_fromUtf8("pushButton_CL_apply"))
        self.verticalLayout_11.addWidget(self.pushButton_CL_apply)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        self.stackedWidget.addWidget(self.page_CL)
        self.verticalLayout_7.addWidget(self.stackedWidget)
        self.verticalLayout_L.addLayout(self.verticalLayout_7)
        self.layoutWidget1 = QtGui.QWidget(self.splitter)
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_AO = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_AO.setMargin(0)
        self.verticalLayout_AO.setObjectName(_fromUtf8("verticalLayout_AO"))
        self.label_AL = QtGui.QLabel(self.layoutWidget1)
        self.label_AL.setText(QtGui.QApplication.translate("root", "Associated Lights:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_AL.setObjectName(_fromUtf8("label_AL"))
        self.verticalLayout_AO.addWidget(self.label_AL)
        self.splitter_2 = QtGui.QSplitter(self.layoutWidget1)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.listWidget_AL = QtGui.QListWidget(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_AL.sizePolicy().hasHeightForWidth())
        self.listWidget_AL.setSizePolicy(sizePolicy)
        self.listWidget_AL.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget_AL.setMaximumSize(QtCore.QSize(16777215, 130))
        self.listWidget_AL.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.listWidget_AL.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_AL.setObjectName(_fromUtf8("listWidget_AL"))
        self.layoutWidget_2 = QtGui.QWidget(self.splitter_2)
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.pushButton_AL_add = QtGui.QPushButton(self.layoutWidget_2)
        self.pushButton_AL_add.setText(QtGui.QApplication.translate("root", "                      Add                     ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_AL_add.setObjectName(_fromUtf8("pushButton_AL_add"))
        self.verticalLayout_3.addWidget(self.pushButton_AL_add)
        self.pushButton_AL_remove = QtGui.QPushButton(self.layoutWidget_2)
        self.pushButton_AL_remove.setText(QtGui.QApplication.translate("root", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_AL_remove.setObjectName(_fromUtf8("pushButton_AL_remove"))
        self.verticalLayout_3.addWidget(self.pushButton_AL_remove)
        self.label_OBJ = QtGui.QLabel(self.layoutWidget_2)
        self.label_OBJ.setText(QtGui.QApplication.translate("root", "Associated Objects:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_OBJ.setObjectName(_fromUtf8("label_OBJ"))
        self.verticalLayout_3.addWidget(self.label_OBJ)
        self.listWidget_AO = QtGui.QListWidget(self.layoutWidget_2)
        self.listWidget_AO.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.listWidget_AO.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_AO.setObjectName(_fromUtf8("listWidget_AO"))
        self.verticalLayout_3.addWidget(self.listWidget_AO)
        self.pushButton_AO_add = QtGui.QPushButton(self.layoutWidget_2)
        self.pushButton_AO_add.setText(QtGui.QApplication.translate("root", "                      Add                     ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_AO_add.setObjectName(_fromUtf8("pushButton_AO_add"))
        self.verticalLayout_3.addWidget(self.pushButton_AO_add)
        self.pushButton_AO_remove = QtGui.QPushButton(self.layoutWidget_2)
        self.pushButton_AO_remove.setText(QtGui.QApplication.translate("root", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_AO_remove.setObjectName(_fromUtf8("pushButton_AO_remove"))
        self.verticalLayout_3.addWidget(self.pushButton_AO_remove)
        self.verticalLayout_AO.addWidget(self.splitter_2)
        self.layoutWidget2 = QtGui.QWidget(self.splitter)
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_O = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_O.setMargin(0)
        self.verticalLayout_O.setObjectName(_fromUtf8("verticalLayout_O"))
        self.label_Outline = QtGui.QLabel(self.layoutWidget2)
        self.label_Outline.setText(QtGui.QApplication.translate("root", "Overrides:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Outline.setObjectName(_fromUtf8("label_Outline"))
        self.verticalLayout_O.addWidget(self.label_Outline)
        self.listWidget_O = QtGui.QListWidget(self.layoutWidget2)
        self.listWidget_O.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.listWidget_O.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_O.setObjectName(_fromUtf8("listWidget_O"))
        self.verticalLayout_O.addWidget(self.listWidget_O)
        self.pushButton_O_remove = QtGui.QPushButton(self.layoutWidget2)
        self.pushButton_O_remove.setText(QtGui.QApplication.translate("root", "                Remove                ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_O_remove.setObjectName(_fromUtf8("pushButton_O_remove"))
        self.verticalLayout_O.addWidget(self.pushButton_O_remove)
        self.layoutWidget3 = QtGui.QWidget(self.splitter)
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.verticalLayout_P = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_P.setMargin(0)
        self.verticalLayout_P.setObjectName(_fromUtf8("verticalLayout_P"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_SP = QtGui.QLabel(self.layoutWidget3)
        self.label_SP.setText(QtGui.QApplication.translate("root", "Scene Passes:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_SP.setObjectName(_fromUtf8("label_SP"))
        self.verticalLayout.addWidget(self.label_SP)
        self.listWidget_SP = QtGui.QListWidget(self.layoutWidget3)
        self.listWidget_SP.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.listWidget_SP.setDragEnabled(True)
        self.listWidget_SP.setDragDropOverwriteMode(False)
        self.listWidget_SP.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.listWidget_SP.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.listWidget_SP.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_SP.setObjectName(_fromUtf8("listWidget_SP"))
        self.verticalLayout.addWidget(self.listWidget_SP)
        self.pushButton_SP_remove = QtGui.QPushButton(self.layoutWidget3)
        self.pushButton_SP_remove.setText(QtGui.QApplication.translate("root", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_SP_remove.setObjectName(_fromUtf8("pushButton_SP_remove"))
        self.verticalLayout.addWidget(self.pushButton_SP_remove)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_AVP = QtGui.QLabel(self.layoutWidget3)
        self.label_AVP.setText(QtGui.QApplication.translate("root", "Available Passes:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_AVP.setObjectName(_fromUtf8("label_AVP"))
        self.verticalLayout_2.addWidget(self.label_AVP)
        self.listWidget_AVP = QtGui.QListWidget(self.layoutWidget3)
        self.listWidget_AVP.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.listWidget_AVP.setDragEnabled(True)
        self.listWidget_AVP.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.listWidget_AVP.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.listWidget_AVP.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_AVP.setObjectName(_fromUtf8("listWidget_AVP"))
        self.verticalLayout_2.addWidget(self.listWidget_AVP)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_P.addLayout(self.horizontalLayout_2)
        self.verticalLayout_AP = QtGui.QVBoxLayout()
        self.verticalLayout_AP.setObjectName(_fromUtf8("verticalLayout_AP"))
        self.label_AP = QtGui.QLabel(self.layoutWidget3)
        self.label_AP.setText(QtGui.QApplication.translate("root", "Associated Passes:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_AP.setObjectName(_fromUtf8("label_AP"))
        self.verticalLayout_AP.addWidget(self.label_AP)
        self.listWidget_ASP = QtGui.QListWidget(self.layoutWidget3)
        self.listWidget_ASP.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.listWidget_ASP.setDragEnabled(True)
        self.listWidget_ASP.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.listWidget_ASP.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.listWidget_ASP.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_ASP.setObjectName(_fromUtf8("listWidget_ASP"))
        self.verticalLayout_AP.addWidget(self.listWidget_ASP)
        self.pushButton_ASP_remove = QtGui.QPushButton(self.layoutWidget3)
        self.pushButton_ASP_remove.setText(QtGui.QApplication.translate("root", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ASP_remove.setObjectName(_fromUtf8("pushButton_ASP_remove"))
        self.verticalLayout_AP.addWidget(self.pushButton_ASP_remove)
        self.verticalLayout_P.addLayout(self.verticalLayout_AP)
        self.layoutWidget4 = QtGui.QWidget(self.splitter)
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.verticalLayout_AOCM = QtGui.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_AOCM.setMargin(0)
        self.verticalLayout_AOCM.setObjectName(_fromUtf8("verticalLayout_AOCM"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_SCM = QtGui.QVBoxLayout()
        self.verticalLayout_SCM.setObjectName(_fromUtf8("verticalLayout_SCM"))
        self.label_CM_2 = QtGui.QLabel(self.layoutWidget4)
        self.label_CM_2.setText(QtGui.QApplication.translate("root", "Scene Contr. Maps:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_CM_2.setObjectName(_fromUtf8("label_CM_2"))
        self.verticalLayout_SCM.addWidget(self.label_CM_2)
        self.listWidget_SCM = QtGui.QListWidget(self.layoutWidget4)
        self.listWidget_SCM.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.listWidget_SCM.setDragEnabled(True)
        self.listWidget_SCM.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.listWidget_SCM.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.listWidget_SCM.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_SCM.setObjectName(_fromUtf8("listWidget_SCM"))
        self.verticalLayout_SCM.addWidget(self.listWidget_SCM)
        self.pushButton_SCM_add = QtGui.QPushButton(self.layoutWidget4)
        self.pushButton_SCM_add.setText(QtGui.QApplication.translate("root", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_SCM_add.setObjectName(_fromUtf8("pushButton_SCM_add"))
        self.verticalLayout_SCM.addWidget(self.pushButton_SCM_add)
        self.pushButton_SCM_remove = QtGui.QPushButton(self.layoutWidget4)
        self.pushButton_SCM_remove.setText(QtGui.QApplication.translate("root", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_SCM_remove.setObjectName(_fromUtf8("pushButton_SCM_remove"))
        self.verticalLayout_SCM.addWidget(self.pushButton_SCM_remove)
        self.horizontalLayout_5.addLayout(self.verticalLayout_SCM)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_CM = QtGui.QLabel(self.layoutWidget4)
        self.label_CM.setText(QtGui.QApplication.translate("root", "Associated Contr. Maps:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_CM.setObjectName(_fromUtf8("label_CM"))
        self.verticalLayout_4.addWidget(self.label_CM)
        self.listWidget_ACM = QtGui.QListWidget(self.layoutWidget4)
        self.listWidget_ACM.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.listWidget_ACM.setDragEnabled(True)
        self.listWidget_ACM.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.listWidget_ACM.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.listWidget_ACM.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_ACM.setObjectName(_fromUtf8("listWidget_ACM"))
        self.verticalLayout_4.addWidget(self.listWidget_ACM)
        self.pushButton_ACM_add = QtGui.QPushButton(self.layoutWidget4)
        self.pushButton_ACM_add.setText(QtGui.QApplication.translate("root", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ACM_add.setObjectName(_fromUtf8("pushButton_ACM_add"))
        self.verticalLayout_4.addWidget(self.pushButton_ACM_add)
        self.pushButton_ACM_remove = QtGui.QPushButton(self.layoutWidget4)
        self.pushButton_ACM_remove.setText(QtGui.QApplication.translate("root", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ACM_remove.setObjectName(_fromUtf8("pushButton_ACM_remove"))
        self.verticalLayout_4.addWidget(self.pushButton_ACM_remove)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_AOCM.addLayout(self.horizontalLayout_5)
        self.verticalLayout_AOCM2 = QtGui.QVBoxLayout()
        self.verticalLayout_AOCM2.setObjectName(_fromUtf8("verticalLayout_AOCM2"))
        self.label_CM_3 = QtGui.QLabel(self.layoutWidget4)
        self.label_CM_3.setText(QtGui.QApplication.translate("root", "Associated Objects:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_CM_3.setObjectName(_fromUtf8("label_CM_3"))
        self.verticalLayout_AOCM2.addWidget(self.label_CM_3)
        self.listWidget_AOCM = QtGui.QListWidget(self.layoutWidget4)
        self.listWidget_AOCM.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.listWidget_AOCM.setDragEnabled(True)
        self.listWidget_AOCM.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.listWidget_AOCM.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.listWidget_AOCM.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_AOCM.setObjectName(_fromUtf8("listWidget_AOCM"))
        self.verticalLayout_AOCM2.addWidget(self.listWidget_AOCM)
        self.pushButton_AOCM_add = QtGui.QPushButton(self.layoutWidget4)
        self.pushButton_AOCM_add.setText(QtGui.QApplication.translate("root", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_AOCM_add.setObjectName(_fromUtf8("pushButton_AOCM_add"))
        self.verticalLayout_AOCM2.addWidget(self.pushButton_AOCM_add)
        self.pushButton_AOCM_remove = QtGui.QPushButton(self.layoutWidget4)
        self.pushButton_AOCM_remove.setText(QtGui.QApplication.translate("root", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_AOCM_remove.setObjectName(_fromUtf8("pushButton_AOCM_remove"))
        self.verticalLayout_AOCM2.addWidget(self.pushButton_AOCM_remove)
        self.verticalLayout_AOCM.addLayout(self.verticalLayout_AOCM2)
        self.layoutWidget_3 = QtGui.QWidget(self.splitter)
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.verticalLayout_MA = QtGui.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_MA.setMargin(0)
        self.verticalLayout_MA.setObjectName(_fromUtf8("verticalLayout_MA"))
        self.splitter_3 = QtGui.QSplitter(self.layoutWidget_3)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.layoutWidget_4 = QtGui.QWidget(self.splitter_3)
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_OBJ_2 = QtGui.QLabel(self.layoutWidget_4)
        self.label_OBJ_2.setText(QtGui.QApplication.translate("root", "Materials:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_OBJ_2.setObjectName(_fromUtf8("label_OBJ_2"))
        self.verticalLayout_5.addWidget(self.label_OBJ_2)
        self.checkBox_layerOverride_materiral = QtGui.QCheckBox(self.layoutWidget_4)
        self.checkBox_layerOverride_materiral.setEnabled(True)
        self.checkBox_layerOverride_materiral.setText(QtGui.QApplication.translate("root", "Layer Override", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_layerOverride_materiral.setChecked(True)
        self.checkBox_layerOverride_materiral.setObjectName(_fromUtf8("checkBox_layerOverride_materiral"))
        self.verticalLayout_5.addWidget(self.checkBox_layerOverride_materiral)
        self.scrollArea = QtGui.QScrollArea(self.layoutWidget_4)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 136, 274))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.pushButton_CM_black = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_CM_black.setText(QtGui.QApplication.translate("root", "Black", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_CM_black.setObjectName(_fromUtf8("pushButton_CM_black"))
        self.verticalLayout_6.addWidget(self.pushButton_CM_black)
        self.pushButton_CM_blackNoAlpha = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_CM_blackNoAlpha.setText(QtGui.QApplication.translate("root", "Black No Alpha", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_CM_blackNoAlpha.setObjectName(_fromUtf8("pushButton_CM_blackNoAlpha"))
        self.verticalLayout_6.addWidget(self.pushButton_CM_blackNoAlpha)
        self.pushButton_CM_green = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_CM_green.setText(QtGui.QApplication.translate("root", "Green", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_CM_green.setObjectName(_fromUtf8("pushButton_CM_green"))
        self.verticalLayout_6.addWidget(self.pushButton_CM_green)
        self.pushButton_CM_blue = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_CM_blue.setText(QtGui.QApplication.translate("root", "Blue", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_CM_blue.setObjectName(_fromUtf8("pushButton_CM_blue"))
        self.verticalLayout_6.addWidget(self.pushButton_CM_blue)
        self.pushButton_CM_red = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_CM_red.setText(QtGui.QApplication.translate("root", "Red", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_CM_red.setObjectName(_fromUtf8("pushButton_CM_red"))
        self.verticalLayout_6.addWidget(self.pushButton_CM_red)
        self.pushButton_CM_zDepth = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_CM_zDepth.setText(QtGui.QApplication.translate("root", "Z Depth", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_CM_zDepth.setObjectName(_fromUtf8("pushButton_CM_zDepth"))
        self.verticalLayout_6.addWidget(self.pushButton_CM_zDepth)
        self.pushButton_CM_useBackground = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_CM_useBackground.setText(QtGui.QApplication.translate("root", "Use Background", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_CM_useBackground.setObjectName(_fromUtf8("pushButton_CM_useBackground"))
        self.verticalLayout_6.addWidget(self.pushButton_CM_useBackground)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.layoutWidget_5 = QtGui.QWidget(self.splitter_3)
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.verticalLayout_RS = QtGui.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_RS.setMargin(0)
        self.verticalLayout_RS.setObjectName(_fromUtf8("verticalLayout_RS"))
        self.label_OBJ_3 = QtGui.QLabel(self.layoutWidget_5)
        self.label_OBJ_3.setText(QtGui.QApplication.translate("root", "Render Status:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_OBJ_3.setObjectName(_fromUtf8("label_OBJ_3"))
        self.verticalLayout_RS.addWidget(self.label_OBJ_3)
        self.checkBox_layerOverride_status = QtGui.QCheckBox(self.layoutWidget_5)
        self.checkBox_layerOverride_status.setEnabled(True)
        self.checkBox_layerOverride_status.setText(QtGui.QApplication.translate("root", "Layer Override", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_layerOverride_status.setChecked(True)
        self.checkBox_layerOverride_status.setObjectName(_fromUtf8("checkBox_layerOverride_status"))
        self.verticalLayout_RS.addWidget(self.checkBox_layerOverride_status)
        self.checkBox_castsShadows = QtGui.QCheckBox(self.layoutWidget_5)
        self.checkBox_castsShadows.setEnabled(True)
        self.checkBox_castsShadows.setText(QtGui.QApplication.translate("root", "Casts Shadows", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_castsShadows.setChecked(True)
        self.checkBox_castsShadows.setObjectName(_fromUtf8("checkBox_castsShadows"))
        self.verticalLayout_RS.addWidget(self.checkBox_castsShadows)
        self.checkBox_receiveShadows = QtGui.QCheckBox(self.layoutWidget_5)
        self.checkBox_receiveShadows.setText(QtGui.QApplication.translate("root", "Receive Shadows", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_receiveShadows.setChecked(True)
        self.checkBox_receiveShadows.setObjectName(_fromUtf8("checkBox_receiveShadows"))
        self.verticalLayout_RS.addWidget(self.checkBox_receiveShadows)
        self.checkBox_motionBlur = QtGui.QCheckBox(self.layoutWidget_5)
        self.checkBox_motionBlur.setText(QtGui.QApplication.translate("root", "Motion Blur", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_motionBlur.setChecked(True)
        self.checkBox_motionBlur.setObjectName(_fromUtf8("checkBox_motionBlur"))
        self.verticalLayout_RS.addWidget(self.checkBox_motionBlur)
        self.checkBox_primaryVisibility = QtGui.QCheckBox(self.layoutWidget_5)
        self.checkBox_primaryVisibility.setText(QtGui.QApplication.translate("root", "Primary Visibility", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_primaryVisibility.setChecked(True)
        self.checkBox_primaryVisibility.setObjectName(_fromUtf8("checkBox_primaryVisibility"))
        self.verticalLayout_RS.addWidget(self.checkBox_primaryVisibility)
        self.checkBox_smoothShading = QtGui.QCheckBox(self.layoutWidget_5)
        self.checkBox_smoothShading.setText(QtGui.QApplication.translate("root", "Smooth Shading", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_smoothShading.setChecked(True)
        self.checkBox_smoothShading.setObjectName(_fromUtf8("checkBox_smoothShading"))
        self.verticalLayout_RS.addWidget(self.checkBox_smoothShading)
        self.checkBox_visibleInReflections = QtGui.QCheckBox(self.layoutWidget_5)
        self.checkBox_visibleInReflections.setText(QtGui.QApplication.translate("root", "Visible In Reflections", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_visibleInReflections.setChecked(True)
        self.checkBox_visibleInReflections.setObjectName(_fromUtf8("checkBox_visibleInReflections"))
        self.verticalLayout_RS.addWidget(self.checkBox_visibleInReflections)
        self.checkBox_visibleInRefractions = QtGui.QCheckBox(self.layoutWidget_5)
        self.checkBox_visibleInRefractions.setText(QtGui.QApplication.translate("root", "Visible In Refractions", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_visibleInRefractions.setChecked(True)
        self.checkBox_visibleInRefractions.setObjectName(_fromUtf8("checkBox_visibleInRefractions"))
        self.verticalLayout_RS.addWidget(self.checkBox_visibleInRefractions)
        self.checkBox_doubleSided = QtGui.QCheckBox(self.layoutWidget_5)
        self.checkBox_doubleSided.setText(QtGui.QApplication.translate("root", "Double Sided", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_doubleSided.setChecked(True)
        self.checkBox_doubleSided.setTristate(False)
        self.checkBox_doubleSided.setObjectName(_fromUtf8("checkBox_doubleSided"))
        self.verticalLayout_RS.addWidget(self.checkBox_doubleSided)
        self.checkBox_opposite = QtGui.QCheckBox(self.layoutWidget_5)
        self.checkBox_opposite.setEnabled(False)
        self.checkBox_opposite.setText(QtGui.QApplication.translate("root", "Opposite", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_opposite.setChecked(False)
        self.checkBox_opposite.setObjectName(_fromUtf8("checkBox_opposite"))
        self.verticalLayout_RS.addWidget(self.checkBox_opposite)
        self.pushButton_RS_apply = QtGui.QPushButton(self.layoutWidget_5)
        self.pushButton_RS_apply.setText(QtGui.QApplication.translate("root", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_RS_apply.setObjectName(_fromUtf8("pushButton_RS_apply"))
        self.verticalLayout_RS.addWidget(self.pushButton_RS_apply)
        self.verticalLayout_MA.addWidget(self.splitter_3)
        self.horizontalLayout.addWidget(self.splitter)
        root.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(root)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        root.setStatusBar(self.statusbar)
        self.actionImport_Layers = QtGui.QAction(root)
        self.actionImport_Layers.setText(QtGui.QApplication.translate("root", "Import Layers ", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport_Layers.setObjectName(_fromUtf8("actionImport_Layers"))
        self.actionExport_Layers = QtGui.QAction(root)
        self.actionExport_Layers.setText(QtGui.QApplication.translate("root", "Export Layers", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport_Layers.setObjectName(_fromUtf8("actionExport_Layers"))
        self.actionRefresh = QtGui.QAction(root)
        self.actionRefresh.setText(QtGui.QApplication.translate("root", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRefresh.setObjectName(_fromUtf8("actionRefresh"))

        self.retranslateUi(root)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(root)

    def retranslateUi(self, root):
        pass

