# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MRRenderLayerPassManager.ui'
#
# Created: Wed Jan 11 23:58:09 2012
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_root(object):
    def setupUi(self, root):
        root.setObjectName(_fromUtf8("root"))
        root.resize(1235, 585)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        root.setFont(font)
        root.setWindowTitle(QtGui.QApplication.translate("root", "Mental Ray Render Layer Manager V1.0 (37digital)", None, QtGui.QApplication.UnicodeUTF8))
        root.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtGui.QWidget(root)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1221, 568))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_RL = QtGui.QLabel(self.widget)
        self.label_RL.setText(QtGui.QApplication.translate("root", "Render Layers", None, QtGui.QApplication.UnicodeUTF8))
        self.label_RL.setObjectName(_fromUtf8("label_RL"))
        self.verticalLayout_7.addWidget(self.label_RL)
        self.listWidget_L = QtGui.QListWidget(self.widget)
        self.listWidget_L.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.listWidget_L.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_L.setObjectName(_fromUtf8("listWidget_L"))
        self.verticalLayout_7.addWidget(self.listWidget_L)
        self.pushButton_L_add = QtGui.QPushButton(self.widget)
        self.pushButton_L_add.setText(QtGui.QApplication.translate("root", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_L_add.setObjectName(_fromUtf8("pushButton_L_add"))
        self.verticalLayout_7.addWidget(self.pushButton_L_add)
        self.pushButton_L_remove = QtGui.QPushButton(self.widget)
        self.pushButton_L_remove.setText(QtGui.QApplication.translate("root", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_L_remove.setObjectName(_fromUtf8("pushButton_L_remove"))
        self.verticalLayout_7.addWidget(self.pushButton_L_remove)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.pushButton_CSRL = QtGui.QPushButton(self.widget)
        self.pushButton_CSRL.setText(QtGui.QApplication.translate("root", "Copy Selected Render Layer", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_CSRL.setObjectName(_fromUtf8("pushButton_CSRL"))
        self.verticalLayout_9.addWidget(self.pushButton_CSRL)
        self.pushButton_ESRL = QtGui.QPushButton(self.widget)
        self.pushButton_ESRL.setText(QtGui.QApplication.translate("root", "Export Selected Render Layers", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ESRL.setObjectName(_fromUtf8("pushButton_ESRL"))
        self.verticalLayout_9.addWidget(self.pushButton_ESRL)
        self.pushButton_IRL = QtGui.QPushButton(self.widget)
        self.pushButton_IRL.setText(QtGui.QApplication.translate("root", "Import Render Layers", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_IRL.setObjectName(_fromUtf8("pushButton_IRL"))
        self.verticalLayout_9.addWidget(self.pushButton_IRL)
        self.verticalLayout_7.addLayout(self.verticalLayout_9)
        self.pushButton_L_apply = QtGui.QPushButton(self.widget)
        self.pushButton_L_apply.setText(QtGui.QApplication.translate("root", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_L_apply.setObjectName(_fromUtf8("pushButton_L_apply"))
        self.verticalLayout_7.addWidget(self.pushButton_L_apply)
        self.pushButton_L_refresh = QtGui.QPushButton(self.widget)
        self.pushButton_L_refresh.setText(QtGui.QApplication.translate("root", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_L_refresh.setObjectName(_fromUtf8("pushButton_L_refresh"))
        self.verticalLayout_7.addWidget(self.pushButton_L_refresh)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.line_3 = QtGui.QFrame(self.widget)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout.addWidget(self.line_3)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_OBJ = QtGui.QLabel(self.widget)
        self.label_OBJ.setText(QtGui.QApplication.translate("root", "Associated Objects:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_OBJ.setObjectName(_fromUtf8("label_OBJ"))
        self.verticalLayout_6.addWidget(self.label_OBJ)
        self.listWidget_AO = QtGui.QListWidget(self.widget)
        self.listWidget_AO.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.listWidget_AO.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_AO.setObjectName(_fromUtf8("listWidget_AO"))
        self.verticalLayout_6.addWidget(self.listWidget_AO)
        self.pushButton_AO_add = QtGui.QPushButton(self.widget)
        self.pushButton_AO_add.setText(QtGui.QApplication.translate("root", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_AO_add.setObjectName(_fromUtf8("pushButton_AO_add"))
        self.verticalLayout_6.addWidget(self.pushButton_AO_add)
        self.pushButton_AO_remove = QtGui.QPushButton(self.widget)
        self.pushButton_AO_remove.setText(QtGui.QApplication.translate("root", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_AO_remove.setObjectName(_fromUtf8("pushButton_AO_remove"))
        self.verticalLayout_6.addWidget(self.pushButton_AO_remove)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.line_4 = QtGui.QFrame(self.widget)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.horizontalLayout.addWidget(self.line_4)
        self.verticalLayout_Obj_2 = QtGui.QVBoxLayout()
        self.verticalLayout_Obj_2.setObjectName(_fromUtf8("verticalLayout_Obj_2"))
        self.label_Outline = QtGui.QLabel(self.widget)
        self.label_Outline.setText(QtGui.QApplication.translate("root", "Overrides:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Outline.setObjectName(_fromUtf8("label_Outline"))
        self.verticalLayout_Obj_2.addWidget(self.label_Outline)
        self.listWidget_O = QtGui.QListWidget(self.widget)
        self.listWidget_O.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.listWidget_O.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_O.setObjectName(_fromUtf8("listWidget_O"))
        self.verticalLayout_Obj_2.addWidget(self.listWidget_O)
        self.pushButton_O_add = QtGui.QPushButton(self.widget)
        self.pushButton_O_add.setText(QtGui.QApplication.translate("root", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_O_add.setObjectName(_fromUtf8("pushButton_O_add"))
        self.verticalLayout_Obj_2.addWidget(self.pushButton_O_add)
        self.pushButton_O_remove = QtGui.QPushButton(self.widget)
        self.pushButton_O_remove.setText(QtGui.QApplication.translate("root", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_O_remove.setObjectName(_fromUtf8("pushButton_O_remove"))
        self.verticalLayout_Obj_2.addWidget(self.pushButton_O_remove)
        self.horizontalLayout.addLayout(self.verticalLayout_Obj_2)
        self.horizontalLayout_7.addLayout(self.horizontalLayout)
        self.line = QtGui.QFrame(self.widget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_7.addWidget(self.line)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_SP = QtGui.QLabel(self.widget)
        self.label_SP.setText(QtGui.QApplication.translate("root", "Scene Passes:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_SP.setObjectName(_fromUtf8("label_SP"))
        self.verticalLayout.addWidget(self.label_SP)
        self.listWidget_SP = QtGui.QListWidget(self.widget)
        self.listWidget_SP.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.listWidget_SP.setDragEnabled(True)
        self.listWidget_SP.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.listWidget_SP.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.listWidget_SP.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_SP.setObjectName(_fromUtf8("listWidget_SP"))
        self.verticalLayout.addWidget(self.listWidget_SP)
        self.pushButton_SP_remove = QtGui.QPushButton(self.widget)
        self.pushButton_SP_remove.setText(QtGui.QApplication.translate("root", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_SP_remove.setObjectName(_fromUtf8("pushButton_SP_remove"))
        self.verticalLayout.addWidget(self.pushButton_SP_remove)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_AVP = QtGui.QLabel(self.widget)
        self.label_AVP.setText(QtGui.QApplication.translate("root", "Available Passes:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_AVP.setObjectName(_fromUtf8("label_AVP"))
        self.verticalLayout_2.addWidget(self.label_AVP)
        self.listWidget_AVP = QtGui.QListWidget(self.widget)
        self.listWidget_AVP.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.listWidget_AVP.setDragEnabled(True)
        self.listWidget_AVP.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.listWidget_AVP.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.listWidget_AVP.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_AVP.setObjectName(_fromUtf8("listWidget_AVP"))
        self.verticalLayout_2.addWidget(self.listWidget_AVP)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_AP = QtGui.QVBoxLayout()
        self.verticalLayout_AP.setObjectName(_fromUtf8("verticalLayout_AP"))
        self.label_AP = QtGui.QLabel(self.widget)
        self.label_AP.setText(QtGui.QApplication.translate("root", "Associated Passes:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_AP.setObjectName(_fromUtf8("label_AP"))
        self.verticalLayout_AP.addWidget(self.label_AP)
        self.listWidget_ASP = QtGui.QListWidget(self.widget)
        self.listWidget_ASP.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.listWidget_ASP.setDragEnabled(True)
        self.listWidget_ASP.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.listWidget_ASP.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.listWidget_ASP.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_ASP.setObjectName(_fromUtf8("listWidget_ASP"))
        self.verticalLayout_AP.addWidget(self.listWidget_ASP)
        self.pushButton_ASP_add = QtGui.QPushButton(self.widget)
        self.pushButton_ASP_add.setText(QtGui.QApplication.translate("root", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ASP_add.setObjectName(_fromUtf8("pushButton_ASP_add"))
        self.verticalLayout_AP.addWidget(self.pushButton_ASP_add)
        self.pushButton_ASP_remove = QtGui.QPushButton(self.widget)
        self.pushButton_ASP_remove.setText(QtGui.QApplication.translate("root", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ASP_remove.setObjectName(_fromUtf8("pushButton_ASP_remove"))
        self.verticalLayout_AP.addWidget(self.pushButton_ASP_remove)
        self.verticalLayout_3.addLayout(self.verticalLayout_AP)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.line_2 = QtGui.QFrame(self.widget)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_6.addWidget(self.line_2)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_SCM = QtGui.QVBoxLayout()
        self.verticalLayout_SCM.setObjectName(_fromUtf8("verticalLayout_SCM"))
        self.label_CM_2 = QtGui.QLabel(self.widget)
        self.label_CM_2.setText(QtGui.QApplication.translate("root", "Scene Contribution Maps:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_CM_2.setObjectName(_fromUtf8("label_CM_2"))
        self.verticalLayout_SCM.addWidget(self.label_CM_2)
        self.listWidget_SCM = QtGui.QListWidget(self.widget)
        self.listWidget_SCM.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.listWidget_SCM.setDragEnabled(True)
        self.listWidget_SCM.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.listWidget_SCM.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.listWidget_SCM.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_SCM.setObjectName(_fromUtf8("listWidget_SCM"))
        self.verticalLayout_SCM.addWidget(self.listWidget_SCM)
        self.pushButton_SCM_add = QtGui.QPushButton(self.widget)
        self.pushButton_SCM_add.setText(QtGui.QApplication.translate("root", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_SCM_add.setObjectName(_fromUtf8("pushButton_SCM_add"))
        self.verticalLayout_SCM.addWidget(self.pushButton_SCM_add)
        self.pushButton_SCM_remove = QtGui.QPushButton(self.widget)
        self.pushButton_SCM_remove.setText(QtGui.QApplication.translate("root", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_SCM_remove.setObjectName(_fromUtf8("pushButton_SCM_remove"))
        self.verticalLayout_SCM.addWidget(self.pushButton_SCM_remove)
        self.horizontalLayout_5.addLayout(self.verticalLayout_SCM)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_CM = QtGui.QLabel(self.widget)
        self.label_CM.setText(QtGui.QApplication.translate("root", "Associated Contribution Maps:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_CM.setObjectName(_fromUtf8("label_CM"))
        self.verticalLayout_4.addWidget(self.label_CM)
        self.listWidget_ACM = QtGui.QListWidget(self.widget)
        self.listWidget_ACM.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.listWidget_ACM.setDragEnabled(True)
        self.listWidget_ACM.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.listWidget_ACM.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.listWidget_ACM.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_ACM.setObjectName(_fromUtf8("listWidget_ACM"))
        self.verticalLayout_4.addWidget(self.listWidget_ACM)
        self.pushButton_ACM_add = QtGui.QPushButton(self.widget)
        self.pushButton_ACM_add.setText(QtGui.QApplication.translate("root", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ACM_add.setObjectName(_fromUtf8("pushButton_ACM_add"))
        self.verticalLayout_4.addWidget(self.pushButton_ACM_add)
        self.pushButton_ACM_remove = QtGui.QPushButton(self.widget)
        self.pushButton_ACM_remove.setText(QtGui.QApplication.translate("root", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ACM_remove.setObjectName(_fromUtf8("pushButton_ACM_remove"))
        self.verticalLayout_4.addWidget(self.pushButton_ACM_remove)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.verticalLayout_AOCM = QtGui.QVBoxLayout()
        self.verticalLayout_AOCM.setObjectName(_fromUtf8("verticalLayout_AOCM"))
        self.label_CM_3 = QtGui.QLabel(self.widget)
        self.label_CM_3.setText(QtGui.QApplication.translate("root", "Associated Objects:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_CM_3.setObjectName(_fromUtf8("label_CM_3"))
        self.verticalLayout_AOCM.addWidget(self.label_CM_3)
        self.listWidget_AOCM = QtGui.QListWidget(self.widget)
        self.listWidget_AOCM.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.listWidget_AOCM.setDragEnabled(True)
        self.listWidget_AOCM.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.listWidget_AOCM.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.listWidget_AOCM.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listWidget_AOCM.setObjectName(_fromUtf8("listWidget_AOCM"))
        self.verticalLayout_AOCM.addWidget(self.listWidget_AOCM)
        self.pushButton_AOCM_add = QtGui.QPushButton(self.widget)
        self.pushButton_AOCM_add.setText(QtGui.QApplication.translate("root", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_AOCM_add.setObjectName(_fromUtf8("pushButton_AOCM_add"))
        self.verticalLayout_AOCM.addWidget(self.pushButton_AOCM_add)
        self.pushButton_AOCM_remove = QtGui.QPushButton(self.widget)
        self.pushButton_AOCM_remove.setText(QtGui.QApplication.translate("root", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_AOCM_remove.setObjectName(_fromUtf8("pushButton_AOCM_remove"))
        self.verticalLayout_AOCM.addWidget(self.pushButton_AOCM_remove)
        self.verticalLayout_5.addLayout(self.verticalLayout_AOCM)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        root.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(root)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        root.setStatusBar(self.statusbar)

        self.retranslateUi(root)
        QtCore.QMetaObject.connectSlotsByName(root)

    def retranslateUi(self, root):
        pass

