# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '37checkTools2.ui'
#
# Created: Tue May 22 11:06:18 2012
#      by: PyQt4 UI code generator 4.6-snapshot-20090810
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("checkTools")
        Frame.resize(400, 850)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.textEdit = QtGui.QTextEdit(Frame)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 381, 211))
        self.textEdit.setObjectName("textEdit")
        self.doubleDisplay = QtGui.QPushButton(Frame)
        self.doubleDisplay.setGeometry(QtCore.QRect(20, 350, 361, 23))
        self.doubleDisplay.setObjectName("doubleDisplay")
        self.baseInfo = QtGui.QPushButton(Frame)
        self.baseInfo.setGeometry(QtCore.QRect(20, 230, 361, 23))
        self.baseInfo.setObjectName("baseInfo")
        self.reRangeUV = QtGui.QPushButton(Frame)
        self.reRangeUV.setGeometry(QtCore.QRect(20, 430, 361, 23))
        self.reRangeUV.setObjectName("reRangeUV")
        self.deleteDisplayLayer = QtGui.QPushButton(Frame)
        self.deleteDisplayLayer.setGeometry(QtCore.QRect(20, 590, 361, 23))
        self.deleteDisplayLayer.setObjectName("deleteDisplayLayer")
        self.zeroObject = QtGui.QPushButton(Frame)
        self.zeroObject.setGeometry(QtCore.QRect(20, 310, 361, 23))
        self.zeroObject.setObjectName("zeroObject")
        self.deleteLight = QtGui.QPushButton(Frame)
        self.deleteLight.setGeometry(QtCore.QRect(20, 550, 361, 23))
        self.deleteLight.setObjectName("deleteLight")
        self.shapeAndTransformName = QtGui.QPushButton(Frame)
        self.shapeAndTransformName.setGeometry(QtCore.QRect(20, 270, 361, 23))
        self.shapeAndTransformName.setObjectName("shapeAndTransformName")
        self.deleteCamera = QtGui.QPushButton(Frame)
        self.deleteCamera.setGeometry(QtCore.QRect(20, 510, 361, 23))
        self.deleteCamera.setObjectName("deleteCamera")
        self.unloadPlugin = QtGui.QPushButton(Frame)
        self.unloadPlugin.setGeometry(QtCore.QRect(20, 750, 361, 23))
        self.unloadPlugin.setObjectName("unloadPlugin")
        self.fiveFace = QtGui.QPushButton(Frame)
        self.fiveFace.setGeometry(QtCore.QRect(20, 390, 361, 23))
        self.fiveFace.setObjectName("fiveFace")
        self.deleteHistory = QtGui.QPushButton(Frame)
        self.deleteHistory.setGeometry(QtCore.QRect(20, 470, 361, 23))
        self.deleteHistory.setObjectName("deleteHistory")
        self.deleteRenderLayer = QtGui.QPushButton(Frame)
        self.deleteRenderLayer.setGeometry(QtCore.QRect(20, 630, 361, 23))
        self.deleteRenderLayer.setObjectName("deleteRenderLayer")
        self.deleteUnknow = QtGui.QPushButton(Frame)
        self.deleteUnknow.setGeometry(QtCore.QRect(20, 790, 361, 23))
        self.deleteUnknow.setObjectName("deleteUnknow")
        self.deleteEmptyGroup = QtGui.QPushButton(Frame)
        self.deleteEmptyGroup.setGeometry(QtCore.QRect(20, 670, 361, 23))
        self.deleteEmptyGroup.setObjectName("deleteEmptyGroup")
        self.faceNormal = QtGui.QPushButton(Frame)
        self.faceNormal.setGeometry(QtCore.QRect(20, 710, 361, 23))
        self.faceNormal.setObjectName("faceNormal")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(QtGui.QApplication.translate("Frame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        Frame.setProperty("+command", QtGui.QApplication.translate("Frame", "\"t = modelCheckTools()\"", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleDisplay.setText(QtGui.QApplication.translate("Frame", "doubleDisplay", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleDisplay.setProperty("+command", QtGui.QApplication.translate("Frame", "\"t.doubleDisplay()\"", None, QtGui.QApplication.UnicodeUTF8))
        self.baseInfo.setText(QtGui.QApplication.translate("Frame", "baseInfo", None, QtGui.QApplication.UnicodeUTF8))
        self.baseInfo.setProperty("+command", QtGui.QApplication.translate("Frame", "\"t.baseInfo()\"", None, QtGui.QApplication.UnicodeUTF8))
        self.reRangeUV.setText(QtGui.QApplication.translate("Frame", "reRangeUV", None, QtGui.QApplication.UnicodeUTF8))
        self.reRangeUV.setProperty("+command", QtGui.QApplication.translate("Frame", "\"t.reRangeUV()\"", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteDisplayLayer.setText(QtGui.QApplication.translate("Frame", "deleteDisplayLayer", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteDisplayLayer.setProperty("+command", QtGui.QApplication.translate("Frame", "\"t.deleteDisplayLayer()\"", None, QtGui.QApplication.UnicodeUTF8))
        self.zeroObject.setText(QtGui.QApplication.translate("Frame", "zeroObject", None, QtGui.QApplication.UnicodeUTF8))
        self.zeroObject.setProperty("+command", QtGui.QApplication.translate("Frame", "\"t.zeroObject()\"", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteLight.setText(QtGui.QApplication.translate("Frame", "deleteLight", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteLight.setProperty("+command", QtGui.QApplication.translate("Frame", "\"t.deleteLight()\"", None, QtGui.QApplication.UnicodeUTF8))
        self.shapeAndTransformName.setText(QtGui.QApplication.translate("Frame", "shapeAndTransformName", None, QtGui.QApplication.UnicodeUTF8))
        self.shapeAndTransformName.setProperty("+command", QtGui.QApplication.translate("Frame", "\"t.shapeAndTransformName()\"", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteCamera.setText(QtGui.QApplication.translate("Frame", "deleteCamera", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteCamera.setProperty("+command", QtGui.QApplication.translate("Frame", "\"t.deleteCamera()\"", None, QtGui.QApplication.UnicodeUTF8))
        self.unloadPlugin.setText(QtGui.QApplication.translate("Frame", "unloadPlugins", None, QtGui.QApplication.UnicodeUTF8))
        self.unloadPlugin.setProperty("+command", QtGui.QApplication.translate("Frame", "\"t.unloadPlugins()\"", None, QtGui.QApplication.UnicodeUTF8))
        self.fiveFace.setText(QtGui.QApplication.translate("Frame", "fiveFace", None, QtGui.QApplication.UnicodeUTF8))
        self.fiveFace.setProperty("+command", QtGui.QApplication.translate("Frame", "\"t.fiveFace()\"", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteHistory.setText(QtGui.QApplication.translate("Frame", "deleteHistory", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteHistory.setProperty("+command", QtGui.QApplication.translate("Frame", "\"t.deleteHistory()\"", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteRenderLayer.setText(QtGui.QApplication.translate("Frame", "deleteRenderLayer", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteRenderLayer.setProperty("+command", QtGui.QApplication.translate("Frame", "\"t.deleteRenderLayer()\"", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteUnknow.setText(QtGui.QApplication.translate("Frame", "deleteUnknow", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteUnknow.setProperty("+command", QtGui.QApplication.translate("Frame", "\"t.deleteUnknow()\"", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteEmptyGroup.setText(QtGui.QApplication.translate("Frame", "deleteEmptyGroup", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteEmptyGroup.setProperty("+command", QtGui.QApplication.translate("Frame", "\"t.deleteEmptyGroup()\"", None, QtGui.QApplication.UnicodeUTF8))
        self.faceNormal.setText(QtGui.QApplication.translate("Frame", "faceNormal", None, QtGui.QApplication.UnicodeUTF8))

